base_url = "https://claytonjgilmer.github.io"
compile_sass = true
generate_feed = true
title = "clayton's site"
description = "malware research and some other bits"
theme = "after-dark"

taxonomies = [
    {name = "categories", feed = true},
]

[markdown]
highlight-code = true

[extra]
author = "Clayton Gilmer"
after_dark_menu = [
    {url = "$BASE_URL", name = "home"},
    {url = "$BASE_URL/categories", name = "categories"},
    {url = "https://github.com/claytonjgilmer", name = "github"},
]
after_dark_title = "clayton's site"
